CREATE OR REPLACE TABLE DEMO_SCHEMA.DUMMY_ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SHIP_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    TOTAL_AMOUNT NUMBER(12,2),
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    PAYMENT_METHOD VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)